version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/server/node"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/server/java"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      jetty:
        patterns:
          - "org.eclipse.jetty:*"
          - "org.glassfish.jersey.*"
      jackson:
        patterns:
          - "com.fasterxml.jackson*"
          - "org.glassfish.jersey.media:jersey-media-json-jackson"
      slf4j:
        patterns:
          - "org.slf4j:*"
  - package-ecosystem: "nuget"
    directory: "/server/csharp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      Microsoft:
        patterns:
          - "Microsoft*"
      Npgsql:
        patterns:
          - "Npgsql*"
  - package-ecosystem: "npm"
    directory: "/client/react"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/client/html"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
