version: "3"

services:
  server-node:
    build: server/node/
    environment:
      - OPA_URL=http://opa:8181
      - DATABASE_URL=postgresql://postgres:schmickethub@database-node:5432/postgres?schema=public
    ports:
      - "4000:4000"
    depends_on:
      - database-node
      - opa
    profiles:
      - node

  database-node:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - "./server/node/database/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: schmickethub
    profiles:
      - node

  # TODO
  # server-java:
  #   build: server/java/
  #   profiles:
  #     - java
  #   depends_on:
  #     - opa

  # TODO
  # client-html:

  # TODO
  # client-react:

  # TODO
  # server-csharp:

  opa:
    image: ${OPA_IMAGE:-docker.io/openpolicyagent/opa:latest}
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - --log-level=debug
      - policies
    working_dir: /work
    volumes:
      - ./policies:/work/policies

  integration-tests:
    image: ghcr.io/orange-opensource/hurl:latest
    volumes:
      - ./tests:/tests
    command:
      - --test
      - --retry=10
      - --verbose
      - --report-junit=tests/api/report.xml
      - tests/api/basic.hurl
    environment:
      - HURL_host=server-${VARIANT:-node}
    profiles:
      - tools
