services:
  server-node:
    build: server/node/
    hostname: server
    profiles:
      - node
    environment:
      - SERVER_PORT=4000
      - OPA_URL=http://opa:8181
      - DATABASE_URL=postgresql://postgres:schmickethub@database:5432/postgres?schema=public
    depends_on:
      - database
      - opa
    expose:
      - 4000

  server-csharp:
    build: server/csharp/
    hostname: server
    profiles:
      - csharp
    environment:
      OPA_URL: "http://opa:8181"
      DATABASE_CONN_STR: "Host=database;Database=postgres;Username=postgres;Password=schmickethub"
    depends_on:
      - database
      - opa
    expose:
      - 4000

  database:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - "./server/node/database/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: schmickethub
    expose:
      - 5432

  # For manual debugging of the Postgres DB.
  # adminer:
  #   image: adminer
  #   restart: always
  #   expose:
  #     - 8080

  server-java:
    build: server/java/
    hostname: server
    init: true
    environment:
      - OPA_URL=http://opa:8181
    ports:
      - "4000:4000"
    profiles:
      - java
    depends_on:
      - opa

  client-html:
    build: client/html/
    profiles:
      - html
    environment:
      SERVER_HOST: localhost
      SERVER_PORT: 4000
      CLIENT_HOST: 127.0.0.1
      CLIENT_SERVER: 3000
    expose:
      - 3000

  client-react:
    build: client/react/
    profiles:
      - react
    expose:
      - 3000
    ports:
      - "3000:3000"

  opa:
    init: true
    build:
      context: .
      dockerfile: opa.Dockerfile
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - --log-level=debug
      - --bundle
      - bundle.tar.gz
    working_dir: /
    volumes:
      - ./policies:/policies

  integration-tests:
    image: ghcr.io/orange-opensource/hurl:latest
    volumes:
      - ./tests:/tests
    command:
      - --test
      - --retry=10
      - --verbose
      - --report-junit=tests/api/report.xml
      - tests/api/basic.hurl
    environment:
      - HURL_host=server
    profiles:
      - tools
