services:
  server-node:
    build: server/node/
    environment:
      - OPA_URL=http://localhost:8181
      - DATABASE_URL=postgresql://postgres:schmickethub@localhost:5432/postgres?schema=public
    # ports:
    #   - "4000:4000"
    depends_on:
      - database
      - opa
    profiles:
      - node
    network_mode: host
    expose:
      - 4000

  database:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    expose:
      - 5432
    volumes:
      - "./server/node/database/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: schmickethub
    network_mode: host

  server-java:
    build: server/java/
    profiles:
      - java
    depends_on:
      - opa
    environment:
      OPA_URL: http://localhost:8181

  client-html:
    build: client/html/
    environment:
      SERVER_HOST: localhost
      SERVER_PORT: 4000
      CLIENT_HOST: 127.0.0.1
      CLIENT_SERVER: 3000
    profiles:
      - html
    expose:
      - 3000
    network_mode: host

  client-react:
    build: client/react/
    network_mode: host
    profiles:
      - react
    expose:
      - 3000

  # TODO
  # server-csharp:

  opa:
    image: ${OPA_IMAGE:-docker.io/openpolicyagent/opa:latest}
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - --log-level=debug
      - policies
    working_dir: /work
    volumes:
      - ./policies:/work/policies

  integration-tests:
    image: ghcr.io/orange-opensource/hurl:latest
    volumes:
      - ./tests:/tests
    command:
      - --test
      - --retry=10
      - --verbose
      - --report-junit=tests/api/report.xml
      - tests/api/basic.hurl
    environment:
      - HURL_host=server-${VARIANT:-node}
    profiles:
      - tools
