services:
  proxy:
    image: caddy:2.8-alpine
    volumes:
      - ${PWD}/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
    command:
      - caddy
      - run
    depends_on:
      - dex

  dex:
    image: ghcr.io/dexidp/dex:latest
    volumes:
      - ${PWD}/dex/dex.yml:/config.yml
    command:
      - dex
      - serve
      - /config.yml
    ports:
      - 5556:5556
    expose:
      - 5556
  server-node:
    build: server/node/
    profiles:
      - node
    environment:
      - OPA_URL=http://opa:8181
      - DATABASE_URL=postgresql://postgres:schmickethub@database:5432/postgres?schema=public
    depends_on:
      - database
      - opa
    expose:
      - 4000

  server-csharp:
    build: server/csharp/
    profiles:
      - csharp
    environment:
      OPA_URL: "http://localhost:8181"
      DATABASE_CONN_STR: "Host=localhost;Database=postgres;Username=postgres;Password=schmickethub"
    depends_on:
      - database
      - opa
    network_mode: host
    expose:
      - 4000

  database:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - "./server/node/database/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: schmickethub
    expose:
      - 5432

  # For manual debugging of the Postgres DB.
  # adminer:
  #   image: adminer
  #   restart: always
  #   network_mode: host
  #   expose:
  #     - 8080

  server-java:
    build: server/java/
    init: true
    environment:
      - OPA_URL=http://opa:8181
    ports:
      - "4000:4000"
    profiles:
      - java
    depends_on:
      - opa

  client-html:
    build: client/html/
    profiles:
      - html
    environment:
      SERVER_HOST: localhost
      SERVER_PORT: 4000
      CLIENT_HOST: 127.0.0.1
      CLIENT_SERVER: 3000
    network_mode: host
    expose:
      - 3000

  client-react:
    build: client/react/
    profiles:
      - react
    expose:
      - 3000

  opa:
    image: ${OPA_IMAGE:-docker.io/openpolicyagent/opa:latest}
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - --log-level=debug
      - policies
    working_dir: /work
    volumes:
      - ./policies:/work/policies

  integration-tests:
    image: ghcr.io/orange-opensource/hurl:latest
    volumes:
      - ./tests:/tests
    command:
      - --test
      - --retry=10
      - --verbose
      - --report-junit=tests/api/report.xml
      - tests/api/basic.hurl
    environment:
      - HURL_host=localhost
    profiles:
      - tools
    network_mode: host
