name: CI

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-react:
    name: opa-react (unit tests)
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - name: setup and test
        run: |
          npm ci
          npm test
        working-directory: client/react/packages/opa-react

  build-clients:
    name: build client
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        client: [html, react]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: open-policy-agent/setup-opa@v2
      - name: build bundle
        run: make policies/bundle.tar.gz
        env:
          OPA: opa
      - name: setup
        run: docker compose --profile ${{ matrix.client }} up --quiet-pull --wait --wait-timeout 300
      - name: smoke test
        run: curl --retry 5 --retry-connrefused --retry-max-time 120 http://127.0.0.1:3000

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        server: [node, csharp, java]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: open-policy-agent/setup-opa@v2
      - name: build bundle
        run: make policies/bundle.tar.gz
        env:
          OPA: opa
      - name: setup
        run: docker compose --profile ${{ matrix.server }} up --quiet-pull --wait --wait-timeout 300
      - name: test
        run: docker compose run --quiet-pull integration-tests
        env:
          VARIANT: ${{ matrix.server }}
      - name: dump logs
        run: docker compose --profile ${{ matrix.server }} logs
        if: failure()
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: Results for server-${{ matrix.server }}
          report_paths: tests/api/report.xml
