name: CI

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  init:
    name: Prereqs
    runs-on: ubuntu-24.04
    steps:
      - uses: StyraInc/styra-init-action@main # ratchet:exclude

  unit-test-policies:
    name: unit test policies
    needs: init
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - run: make test-policies

  unit-test-react:
    name: node packages
    needs: init
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        pkg: [opa-wasm]
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "21.x"
      - uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
      - name: setup and test
        run: |
          npm ci
          npm test
        working-directory: client/react/packages/${{ matrix.pkg }}

  build-clients:
    name: build client
    needs: init
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        client: [html, react]
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: build wasm bundle
        run: |
          curl -Lo eopa https://github.com/StyraInc/enterprise-opa/releases/download/v1.36.2/eopa_Linux_x86_64
          chmod +x ./eopa
          make client/react/public/opa.wasm
        env:
          OPA: ./eopa
        if: ${{ matrix.client == 'react' }}
      - name: setup
        run: docker compose --profile ${{ matrix.client }} up --quiet-pull --wait --wait-timeout 300 --build
        env:
          OPA_DOCKERFILE: enterprise-opa.Dockerfile
          EOPA_LICENSE_KEY: ${{ secrets.EOPA_LICENSE_KEY }}
      - name: smoke test
        run: curl --retry 5 --retry-connrefused --retry-max-time 120 http://127.0.0.1:3000 -v

  test-e2e:
    name: Test E2E
    needs: init
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        server: [node, csharp, aspnetcore, java, springboot]
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: setup
        run: docker compose --profile ${{ matrix.server }} --profile react up --quiet-pull --wait --wait-timeout 300
        env:
          OPA_DOCKERFILE: enterprise-opa.Dockerfile
          EOPA_LICENSE_KEY: ${{ secrets.EOPA_LICENSE_KEY }}
      - name: Install dependencies
        run: npm ci
        working-directory: tests/e2e
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: tests/e2e
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: tests/e2e
        env:
          CONDITIONS: ${{ matrix.server == 'node' || matrix.server == 'csharp' }}
          REASONS: ${{ matrix.server == 'node' || matrix.server == 'java' }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: playwright-report-${{ matrix.server }}
          path: tests/e2e/playwright-report/
          retention-days: 7
      - name: Run hurl API tests
        run: docker compose run --quiet-pull integration-tests
        env:
          HURL_SKIP_CONDITIONS: ${{ matrix.server != 'node' && matrix.server != 'csharp' }}
          HURL_SKIP_MASKING: ${{ matrix.server != 'node' && matrix.server != 'csharp' }}
      - name: dump logs
        run: docker compose --profile ${{ matrix.server }} logs
        if: failure()
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@cf701569b05ccdd861a76b8607a66d76f6fd4857 # v5.5.1
        if: always()
        with:
          check_name: Results for server-${{ matrix.server }}
          report_paths: tests/api/report.xml

  test-e2e-batch:
    name: Test E2E Batching
    needs: init
    runs-on: ubuntu-24.04
    env:
      eopa_license: ${{ secrets.EOPA_LICENSE_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
        if: env.eopa_license != ''
      - name: setup
        run: docker compose --profile node --profile react up --quiet-pull --wait --wait-timeout 300
        env:
          OPA_DOCKERFILE: enterprise-opa.Dockerfile
          EOPA_LICENSE_KEY: ${{ secrets.EOPA_LICENSE_KEY }}
        if: env.eopa_license != ''
      - name: Install dependencies
        run: npm ci
        working-directory: tests/e2e
        if: env.eopa_license != ''
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: tests/e2e
        if: env.eopa_license != ''
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: tests/e2e
        env:
          BATCHING: true
        if: env.eopa_license != ''
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: playwright-report-batching-node
          path: tests/e2e/playwright-report/
          retention-days: 7
        if: env.eopa_license != '' && always()
      - name: dump logs
        run: docker compose --profile node logs
        if: env.eopa_license != '' && always()
